# Site Settings
title: SaifAliMZ's Blog | Technically Amazing
email: saifalimz@gmail.com
description: Technology Blog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.saifalimz.me" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: SaifAliMZ
user_description: Geek. Gamer.
disqus_username: saifalimz

# Social Media
# Remove the item if you don't need it
github_username: saifalimz
facebook_username: saifalimz
twitter_username: saifalimz
instagram_username: xx_saif_ali
linkedin_username: saifalimz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
